format_version: 11
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other

workflows:
  primary:
    stack: "macos-xcode:12.0"
    steps:
      - script:
          inputs:
            - content: echo "Running on macOS Xcode 12.0 stack"