version: 2
updates:
  - package-ecosystem: "bundler"
    directory: '/app'
    schedule:
      interval: 'weekly'
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
