AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Naming/BlockForwarding:
  EnforcedStyle: explicit

Metrics/MethodLength:
  CountAsOne: [ 'array', 'hash', 'heredoc' ]