version: 2.1

# Define orbs
orbs:
  docker: circleci/docker@2.4.0

# Custom commands
commands:
  install_deps:
    description: "Install required dependencies"
    steps:
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y curl jq git

jobs:
  install:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - install_deps
      - docker/install

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          image: $IMAGE_NAME
          tag: latest
      # - docker/push:
      #     image: $IMAGE_NAME
      #     tag: latest

workflows:
  version: 2
  install-and-build:
    jobs:
      - install
      - build:
          requires:
            - install
          context: docker-hub-creds