pipeline:
  agent: 'any'
  parameters:
    - "string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')"
    - "text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')"
    - "boolean(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')"
    - "choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')"
    - "password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')"
  stages:
    - stage: Stage
      steps:
        - echo "test-output-${env.BRANCH_NAME}"
