pipeline:
  agent: 'any'
  triggers:
    - cron('H */4 * * 1-5')
    - pollSCM('H */4 * * 1-5')
    - upstream('upstream-project', 'SUCCESS')
  stages:
    - stage: Stage
      steps:
        - echo "Testing triggers"
