steps:
  - label: ":hammer: Testing"
    command: gem install rubocop && rubocop -l app
    plugins:
      - docker#v5.7.0:
          image: ruby:3.2
  - label: ":docker: Check working directory"
    command: gem install rspec && ls -al app
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app
  - label: ":rspec: gem install rspec && rspec "
    command: gem install rspec && rspec --color app/spec
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app

  - wait: ~

  - label: ":docker: Build image"
    command: docker build . -t migration