steps:
  - label: ":hammer: Linting"
    command: gem install rubocop && rubocop -l app
    plugins:
      - docker#v5.7.0:
          image: ruby:3.2

  - label: ":rspec: Snapshot Testing"
    command: gem install rspec && rspec --require spec_helper.rb --color app/spec
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app

  - wait: ~

  - label: ":docker: Build image"
    command: docker build . -t migration