steps:
  - label: ":hammer: Linting"
    command: 
      - bundle config set --local with 'test'
      - cd app && bundle install
      - rubocop -l app
    plugins:
      - docker#v5.7.0:
          image: ruby:3.2

  - label: ":rspec: Snapshot Testing"
    command: 
      - bundle config set --local with 'test'
      - cd app && bundle install
      - rspec spec
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app

  - wait: ~

  - label: ":docker: Build image"
    command: docker build . -t migration