steps:
  - label: ":hammer: Linting"
    command:
      - cd app && bundle install
      - rubocop -l
    plugins:
      - docker#v5.7.0:
          image: ruby:3.2

  - label: ":rspec: Snapshot Testing"
    command:
      - cd app && bundle install
      - rspec spec
    plugins:
      - docker#v5.9.0:
          image: ruby:3.2
          workdir: /app
