steps:
  - label: ":hammer: Linting"
    command:
      - cd app && bundle install
      - rubocop
    plugins:
      - docker#v5.11.0:
          image: ruby:3.4.5

  - label: ":rspec: Snapshot Testing"
    command:
      - cd app && bundle install
      - rspec spec
    plugins:
      - docker#v5.11.0:
          image: ruby:3.4.5
          workdir: /app
